[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
adapter = { path = "../adapter" }
web = { path = "../web" }
env_logger = "0.11.3"
log = "0.4.22"
tokio = { version = "1.38.0", features = ["macros"] }
